// AUTO-GENERATED.
const String kDevStoreToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc5MDA0NTU1MywiZXhwIjoxNzkwMDUyNzUzfQ.Bf0rAhXeOOZJtJnNVbeEnMMSILvqZeDBXkdxsrtUs_c';
